name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Lint and Test Job
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          # or if you separate dev/test deps: pip install --no-cache-dir -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          flake8 .
      
      - name: Run unit tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

  # 2. Docker Build & Push Job
  docker_build_and_push:
    # This job depends on tests passing
    needs: [lint_and_test]
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      
      # If you need multi-arch images (for arm64, etc.), uncomment these steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: arm64, amd64
      #
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          # If you only need linux/amd64, you can omit 'platforms'
          # For multi-arch:
          # platforms: linux/amd64,linux/arm64
          push: true
          # Use your Docker Hub username/org in the image tag
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myflaskapp:latest